version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(Deps): '

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '
