@_implementationOnly import SwiftSyntax
@_implementationOnly import SwiftSyntaxMacros

/// A type representing data associated with an enum variable switch case.
///
/// This type informs how this variable needs to be initialized,
/// decoded/encoded in the macro expansion phase.
protocol EnumSwitcherVariable: Variable
where CodingLocation == EnumSwitcherLocation, Generated == EnumSwitcherGenerated
{
    /// Creates value expressions for provided enum-case variable.
    ///
    /// Determines the value of enum-case variable to have `CodingKey`
    /// based values or any raw values.
    ///
    /// - Parameters:
    ///   - variable: The variable for which generated.
    ///   - values: The values present in syntax.
    ///   - codingKeys: The map where `CodingKeys` maintained.
    ///   - context: The context in which to perform the macro expansion.
    ///
    /// - Returns: The generated value.
    func keyExpression<Var: EnumCaseVariable>(
        for variable: Var, values: [ExprSyntax],
        codingKeys: CodingKeysMap, context: some MacroExpansionContext
    ) -> EnumVariable.CaseValue

    /// Creates additional enum declarations for enum variable.
    ///
    /// The generated enum is a raw enum of `String` type
    /// and confirms to `CodingKey`.
    ///
    /// - Parameter context: The macro expansion context.
    /// - Returns: The generated enum declaration syntax.
    func codingKeys(
        in context: some MacroExpansionContext
    ) -> MemberBlockItemListSyntax
}

/// Represents the location for decoding/encoding for `EnumSwitcherVariable`.
///
/// These data will be used to generated switch expression syntax and
/// additional code.
package struct EnumSwitcherLocation {
    ///The decoder/encoder syntax to use.
    ///
    /// Represents the decoder/encoder argument syntax for
    /// the `Codable` conformance implementation methods.
    let coder: TokenSyntax
    ///The decoding/encoding container syntax to use.
    ///
    /// Represents the primary container created from decoder/encoder.
    let container: TokenSyntax
    /// The `CodingKey` type.
    ///
    /// Represents the `CodingKeys` type
    /// expression containing all keys.
    let keyType: ExprSyntax
    /// The current enum type.
    ///
    /// Represents the type expression of enum
    /// for which declaration being generated.
    let selfType: ExprSyntax
    /// The current enum value.
    ///
    /// Represents the value expression present
    /// in switch header and compared.
    let selfValue: ExprSyntax
}

/// Represents the syntax generated by `EnumSwitcherVariable`.
///
/// Represents the switch expression with additional prefix code generated.
package struct EnumSwitcherGenerated {
    /// Case specific callback for decoding/encoding case variation.
    ///
    /// The passed token is used by switcher to decode/encode case
    /// variation.
    typealias CoderCallback = (TokenSyntax) -> CodeBlockItemListSyntax
    /// The decoder/encoder for decoding
    /// or encoding enum-case content.
    ///
    /// This decoder/encoder is used for decoding
    /// or encoding enum-case associated variables.
    let coder: TokenSyntax
    /// The switch header expression.
    ///
    /// This expression will be used to switch on
    /// by all the enum-case variables.
    let expr: ExprSyntax
    /// The additional code.
    ///
    /// This code will prepend the switch expression generated.
    let code: CodeBlockItemListSyntax
    /// Whether to add default case for switch statement.
    ///
    /// Only set to true if default case is required for switch.
    /// Depending on this value and if any case is ignored
    /// default case is added.
    let `default`: Bool
    /// The callback to generate case variation data.
    ///
    /// Each enum-case passes its value to this callback
    /// to generate case variation decoding/encoding syntax.
    let action: CoderCallback
}
